### ISSUE TITLE
switch to Pull-Request Workflow!

### ISSUE THREAD

**Issue by elf-pavlik** [apollo-ng/dspace-app-apollong#10]
http://sexysexypenguins.com/2012/08/13/working-with-githubs-pull-request-workflow/

merging always feature/sth -> develop ?

**Comment by elf-pavlik** [comment]
@alice-wl @chron0 @nilclass @ruebezahl @yggi  no one pushes to upstream any more?
i guess i'll put more info in readme and we can close this one?

**Comment by chron0** [comment]
I think we all have made at least one pull-request and merged it now, so I close this one, since we are using it now as the primary workflow. I think it still makes sense, that we can push quick stuff just right in, if we are certain that it won't break develop, but that should be the exception to the default pull-request workflow in order to scale better when more developers are joining.
