### ISSUE TITLE
daily backup of github issues

### ISSUE THREAD

**Issue by elf-pavlik** [apollo-ng/dspace-app-apollong#13]
in case github goes down before we move out to some libre alternative ;)
https://api.github.com/repos/apollo-ng/dspace-client/issues

**Comment by chron0** [comment]
backup running hourly now...

**Comment by nilclass** [comment]
That resource only contains some of the issue data though. "comments" are an additional resource: https://api.github.com/repos/apollo-ng/dspace-client/issues/{issue.number}/comments
and events (state changes, such as "closed") as well: https://api.github.com/repos/apollo-ng/dspace-client/issues/{issue.number}/events
You can also follow the "comments_url" / "events_url" attributes in each issue to get there.

**Comment by chron0** [comment]
if someone writes a wrapper to collect all data we can implement that as well, the "backup" request was dubious to begin with and since github doesn't seem to have a simple interface to get all data at once I don't see the point in investing more time to get the other data deps as well. If we don't trust github to keep the data available, we shouldn't have chosen to use it at all...

If someone has ruby available feel free to play with: https://github.com/zauberlabs/backup-github

**Comment by elf-pavlik** [comment]
i'll take a look at it!

**Comment by alice-wl** [comment]
how about http://gitlabhq.com/

**Comment by elf-pavlik** [comment]
@alice-wl i would like to use gitlab but out of the box it doesn't have public repositories :( i hope we could change it by adjusting before_filters which require authentication and turn it into all public repos... still i don't know if could do that by next hackathon...

**Comment by elf-pavlik** [comment]
@chron0 can you try this one and maybe assign it to yourself again? :)
https://github.com/joeyh/github-backup

**Comment by nilclass** [comment]
Just for reference... http://tosdr.org/#github

**Comment by elf-pavlik** [comment]
move to GitLab #94 will take care of this one :)
