### ISSUE TITLE
implement ContextMenu

### ISSUE THREAD

**Issue by yggi** [apollo-ng/dspace-app-apollong#2]

**Comment by chron0** [comment]
1. Free Map Context: a) Center map here b) Add new Pin c) Add Overlay Feature  d) Where am I?
2. Marker Context: a) Show Feature Details b) Edit Feature (inactive for now) c) Delete Feature (inactive for now)
3. Pin Context a) Center map here b) Add to Overlay c) Delete pin

**Comment by elf-pavlik** [comment]
@chron0 i would like to have a first option in it _pin_ to set center of _user_ focus which may differ from center of _map_ focus ;)

**Comment by elf-pavlik** [comment]
- **As a** person who likes to look around
- **I want** to place a single pin on a map
- **So that I** can pan map still seeing distatnces etc. in relation to location of that pin (rather then center of a map)
- **And I want** to easily _unpin_ map
- **And** that i can remove this pin and map will use it current center as point of focus

**Comment by elf-pavlik** [comment]
all features can also have options on their markers and boxItems to pin them...

**Comment by chron0** [comment]
Basic Context Menu implemented, no Buttons yet....

**Comment by elf-pavlik** [comment]
@chron0 how about this one?

**Comment by nilclass** [comment]
started in "develop", clicking "new feature" works, does nothing though.

**Comment by chron0** [comment]
Integrated Basic mapContext + Styles
